---
author: "Cyber and Infrastructure Security Agency"
branding:
  icon: "clock"
  color: "purple"
description: "Creates pull requests for upstream changes in repositories."
name: "Lineage"

inputs:
  access_token:
    description: "GitHub personal access token."
    required: true
  repo_query:
    description: "GitHub search query to find repositories for pull requests."
    required: true
runs:
  using: "docker"
  image: "Dockerfile"
